version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-exmple-db
    environment:
      POSTGRES_DB: springbootdemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hcadmin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  mongo_data: